модуль Tour.Collections

// From https://docs.microsoft.com/en-us/dotnet/fsharp/tour
// Visit the link above үшін more information on each topic
// You can also find more learning resources at https://fsharp.org/

модуль Lists =

    /// Lists are defined using [ ... ].  This is an empty list.
    болсын list1 = [ ]

    /// This is a list с 3 elements.  ';' is used to separate elements on the same line.
    болсын list2 = [ 1; 2; 3 ]

    /// You can also separate elements by placing them on their own lines.
    болсын list3 = [
        1
        2
        3
    ]

    /// This is a list бастап integers from 1 to 1000
    болсын numberList = [ 1 .. 1000 ]

    /// Lists can also be generated by computations. This is a list containing
    /// all the days бастап the year.
    болсын daysList =
        [ үшін month ішінде 1 .. 12 жасау
              үшін day ішінде 1 .. System.DateTime.DaysInMonth(2017, month) жасау
                  беру System.DateTime(2017, month, day) ]

    // Print the first 5 elements бастап 'daysList' using 'List.take'.
    printfn "The first 5 days бастап 2017 are: %A" (daysList |> List.take 5)

    /// Computations can include conditionals.  This is a list containing the tuples
    /// which are the coordinates бастап the black squares on a chess board.
    болсын blackSquares =
        [ үшін i ішінде 0 .. 7 жасау
              үшін j ішінде 0 .. 7 жасау
                  егер (i+j) % 2 = 1 содан
                      беру (i, j) ]

    /// Lists can be transformed using 'List.map' and other functional programming combinators.
    /// This definition produces a жаңа list by squaring the numbers ішінде numberList, using the pipeline
    /// operator to pass an argument to List.map.
    болсын squares =
        numberList
        |> List.map (функ x -> x*x)

    /// There are many other list combinations. The following computes the sum бастап the squares бастап the
    /// numbers divisible by 3.
    болсын sumOfSquares =
        numberList
        |> List.filter (функ x -> x % 3 = 0)
        |> List.sumBy (функ x -> x * x)

    printfn "The sum бастап the squares бастап numbers up to 1000 that are divisible by 3 is: %d" sumOfSquares


модуль Arrays =

    /// This is the empty array.  Note that the syntax is similar to that бастап Lists, but uses `[| ... |]` instead.
    болсын array1 = [| |]

    /// Arrays are specified using the same range бастап constructs as lists.
    болсын array2 = [| "hello"; "world"; "and"; "hello"; "world"; "again" |]

    /// This is an array бастап numbers from 1 to 1000.
    болсын array3 = [| 1 .. 1000 |]

    /// This is an array containing only the words "hello" and "world".
    болсын array4 =
        [| үшін word ішінде array2 жасау
               егер word.Contains("l") содан
                   беру word |]

    /// This is an array initialized by index and containing the even numbers from 0 to 2000.
    болсын evenNumbers = Array.init 1001 (функ n -> n * 2)

    /// Sub-arrays are extracted using slicing notation.
    болсын evenNumbersSlice = evenNumbers.[0..500]

    // You can loop over arrays and lists using 'үшін' loops.
    үшін word ішінде array4 жасау
        printfn "word: %s" word

    // You can modify the contents бастап an array element by using the left arrow assignment operator.
    //
    // To learn more about this operator, see: https://docs.microsoft.com/dotnet/fsharp/language-reference/values/index#mutable-variables
    array2.[1] <- "WORLD!"

    /// You can transform arrays using 'Array.map' and other functional programming operations.
    /// The following calculates the sum бастап the lengths бастап the words that start с 'h'.
    болсын sumOfLengthsOfWords =
        array2
        |> Array.filter (функ x -> x.StartsWith "h")
        |> Array.sumBy (функ x -> x.Length)

    printfn "The sum бастап the lengths бастап the words ішінде Array 2 is: %d" sumOfLengthsOfWords


модуль Sequences =

    /// This is the empty sequence.
    болсын seq1 = Seq.empty

    /// This a sequence бастап values.
    болсын seq2 = seq { беру "hello"; беру "world"; беру "and"; беру "hello"; беру "world"; беру "again" }

    /// This is an on-demand sequence from 1 to 1000.
    болсын numbersSeq = seq { 1 .. 1000 }

    /// This is a sequence producing the words "hello" and "world"
    болсын seq3 =
        seq { үшін word ішінде seq2 жасау
                  егер word.Contains("l") содан
                      беру word }

    /// This sequence producing the even numbers up to 2000.
    болсын evenNumbers = Seq.init 1001 (функ n -> n * 2)

    болсын rnd = System.Random()

    /// This is an infinite sequence which is a random walk.
    /// This example uses yield! to return each element бастап a subsequence.
    болсын rec randomWalk x =
        seq { беру x
              yield! randomWalk (x + rnd.NextDouble() - 0.5) }

    /// This example shows the first 100 elements бастап the random walk.
    болсын first100ValuesOfRandomWalk =
        randomWalk 5.0
        |> Seq.truncate 100
        |> Seq.toList

    printfn "First 100 elements бастап a random walk: %A" first100ValuesOfRandomWalk
